### ISSUE TITLE
Lens dependency

### ISSUE THREAD

**Issue by NorfairKing** [massysett/rainbow#13]
Rainbow looks to depend on `lens`. Is there any way we could get rid of that dependency? It is _huge_ and I would like to use `rainbow` in a testing library that should have a minimal footprint.

**Comment by massysett** [comment]
Thanks for the comment.  Lens is essential to the design of this library - it uses types that are deeply nested, and allows the user to modify them.  Doing this without Lens is a mess and is not worth it.

For a time I did use microlens, which has a smaller dependency footprint.  However, for quite some time microlens would not compile using a current GHC and package set, a problem Lens has never had for an extended period.  So I stick with Lens because it is so actively maintained.

It would probably be easy to fork the library and have it depend on microlens, or it would be straightforward and tedious to fork it and rewrite it to remove lenses entirely.  I would welcome such a fork - any software that someone else is willing to maintain so that I can use it is a beautiful thing :)

**Comment by NorfairKing** [comment]
@massysett I may be able to change the dependency from lens to microlens, but that wouldn't help if I cannot contribute back the result. Would you be open to accepting such a change?

**Comment by massysett** [comment]
No, past experience showed that using microlens can result in increased maintenance burden - e.g. microlens was not usable with a current GHC and libraries (not the microlens author's fault that GHC and its libraries are not 100% stable, but still.)  Though I do understand that lens has a bigger dependency footprint, changing to microlens is not worth it to me.  Feel free to vendor or fork rainbow though, I have absolutely no objection to that.

**Comment by solomon-b** [comment]
I know you already made a decision, but I would be happy to write a small PR to inline all your lens library usage so that you don't need to depend on any lens related libraries.

**Comment by NorfairKing** [comment]
FWIW: I ended up making https://github.com/NorfairKing/safe-coloured-text instead.

**Comment by solomon-b** [comment]
> FWIW: I ended up making https://github.com/NorfairKing/safe-coloured-text instead.

My point is that `rainbow` can still have a lensy interface without depending on lens at all.
